"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "catppuccin_latte"
format = "$directory$git_branch$git_status$nodejs$python$line_break$character"
right_format = "$cmd_duration$time"

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](blue)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
format = " [$symbol$branch]($style)"
symbol = "git:"
style = "mauve"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "peach"
conflicted = "="
ahead = ">"
behind = "<"
diverged = "<>"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"

[nodejs]
format = " [node $version](green)"

[python]
format = " [py $version](yellow)"

[cmd_duration]
min_time = 500
format = "[$duration](overlay1) "

[time]
disabled = false
format = "[$time](overlay1)"
time_format = "%H:%M"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
