"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "dracula"
format = "$directory$git_branch$git_status$nodejs$python$line_break$character"
right_format = "$cmd_duration$time"

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](blue)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
format = " [$symbol$branch]($style)"
symbol = "git:"
style = "mauve"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "peach"
conflicted = "="
ahead = ">"
behind = "<"
diverged = "<>"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"

[nodejs]
format = " [node $version](green)"

[python]
format = " [py $version](yellow)"

[cmd_duration]
min_time = 500
format = "[$duration](overlay1) "

[time]
disabled = false
format = "[$time](overlay1)"
time_format = "%H:%M"

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
