# Appearance
font_family JetBrainsMono Nerd Font
font_size 13
disable_ligatures always
window_padding_width 8
hide_window_decorations no
macos_titlebar_color background
background_opacity 0.95

# Cursor
cursor_shape block
cursor_blink_interval 0
mouse_hide_wait 3

# Terminal behavior
shell fish -l
shell_integration enabled
confirm_os_window_close 0
copy_on_select clipboard
clipboard_control write-clipboard read-clipboard

# macOS
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

# Dracula
foreground #f8f8f2
background #282a36
selection_foreground #ffffff
selection_background #44475a
cursor #f8f8f2
cursor_text_color background
url_color #8be9fd
active_border_color #bd93f9
inactive_border_color #6272a4
bell_border_color #f1fa8c
active_tab_foreground #282a36
active_tab_background #f8f8f2
inactive_tab_foreground #282a36
inactive_tab_background #6272a4
color0 #21222c
color1 #ff5555
color2 #50fa7b
color3 #f1fa8c
color4 #bd93f9
color5 #ff79c6
color6 #8be9fd
color7 #f8f8f2
color8 #6272a4
color9 #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #d6acff
color13 #ff92df
color14 #a4ffff
color15 #ffffff
